name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
      developmentVersion:
        description: 'Development version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure Git
        run: |
          git config --global user.name "Qameta CI"
          git config --global user.email "ci@qameta.io"
      - name: Save Settings
        run: echo ${BINTRAY_SETTINGS} > ~/.m2/settings.xml
        env:
          BINTRAY_SETTINGS: ${{ secrets.BINTRAY_SETTINGS }}
      - name: Release
        run: |
          ./mvnw release:prepare release:perform -B \
                 -DreleaseVersion=${{ github.event.inputs.releaseVersion }} \
                 -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}-SNAPSHOT
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
